/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vkpdvpfxwbhbilrhghqb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrcGR2cGZ4d2JoYmlscmhnaHFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTc5ODksImV4cCI6MjA3NzQ3Mzk4OX0.VPX3lBAKsA2Qr4yFQhm-VKDHPB-byVN7nGeUf2wjaUc"