import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface Complaint {
  id: number;
  category: string;
  title: string;
  description: string;
  location: string;
  votes: number;
  submittedDate: string;
  status: 'pending' | 'verified' | 'resolved';
  photo: string;
  resolutionImage?: string;
  resolvedDate?: string;
}

export function generateDailySummaryPDF(complaints: Complaint[], municipalName: string) {
  const doc = new jsPDF();
  
  // Add header
  doc.setFillColor(37, 99, 235); // Blue
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text('Daily Summary Report', 105, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.text(municipalName, 105, 30, { align: 'center' });
  
  const today = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
  doc.text(today, 105, 37, { align: 'center' });
  
  // Reset text color
  doc.setTextColor(0, 0, 0);
  
  // Summary Statistics
  const totalCount = complaints.length;
  const pendingCount = complaints.filter(c => c.status === 'pending').length;
  const verifiedCount = complaints.filter(c => c.status === 'verified').length;
  const resolvedCount = complaints.filter(c => c.status === 'resolved').length;
  
  let yPos = 50;
  
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Overview Statistics', 14, yPos);
  
  yPos += 10;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  
  // Stats boxes
  const statsData = [
    ['Total Complaints', totalCount.toString()],
    ['Pending', pendingCount.toString()],
    ['In Progress (Verified)', verifiedCount.toString()],
    ['Resolved', resolvedCount.toString()],
  ];
  
  autoTable(doc, {
    startY: yPos,
    head: [['Metric', 'Count']],
    body: statsData,
    theme: 'grid',
    headStyles: { fillColor: [37, 99, 235], textColor: [255, 255, 255] },
    columnStyles: { 0: { fontStyle: 'bold' } },
    margin: { left: 14, right: 14 },
  });
  
  yPos = (doc as any).lastAutoTable.finalY + 15;
  
  // Category Breakdown
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Category-wise Breakdown', 14, yPos);
  
  yPos += 5;
  
  const categoryGroups: { [key: string]: Complaint[] } = {};
  complaints.forEach(c => {
    if (!categoryGroups[c.category]) {
      categoryGroups[c.category] = [];
    }
    categoryGroups[c.category].push(c);
  });
  
  const categoryData = Object.entries(categoryGroups).map(([category, items]) => {
    const pending = items.filter(c => c.status === 'pending').length;
    const verified = items.filter(c => c.status === 'verified').length;
    const resolved = items.filter(c => c.status === 'resolved').length;
    const resolutionRate = items.length > 0 ? ((resolved / items.length) * 100).toFixed(1) : '0.0';
    
    return [
      category.charAt(0).toUpperCase() + category.slice(1),
      items.length.toString(),
      pending.toString(),
      verified.toString(),
      resolved.toString(),
      `${resolutionRate}%`
    ];
  });
  
  autoTable(doc, {
    startY: yPos,
    head: [['Category', 'Total', 'Pending', 'In Progress', 'Resolved', 'Resolution Rate']],
    body: categoryData,
    theme: 'striped',
    headStyles: { fillColor: [37, 99, 235], textColor: [255, 255, 255] },
    margin: { left: 14, right: 14 },
  });
  
  // Add footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${pageCount}`,
      105,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
    doc.text(
      'Generated by Municipal Complaint Management System',
      105,
      doc.internal.pageSize.height - 5,
      { align: 'center' }
    );
  }
  
  // Save the PDF
  doc.save(`Daily_Summary_Report_${new Date().toISOString().split('T')[0]}.pdf`);
}

export function generateMonthlyAnalyticsPDF(complaints: Complaint[], municipalName: string) {
  const doc = new jsPDF();
  
  // Add header
  doc.setFillColor(147, 51, 234); // Purple
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text('Monthly Analytics Report', 105, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.text(municipalName, 105, 30, { align: 'center' });
  
  const currentMonth = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long'
  });
  doc.text(currentMonth, 105, 37, { align: 'center' });
  
  doc.setTextColor(0, 0, 0);
  
  let yPos = 50;
  
  // Monthly Statistics
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Monthly Performance Metrics', 14, yPos);
  
  yPos += 10;
  
  const totalCount = complaints.length;
  const resolvedCount = complaints.filter(c => c.status === 'resolved').length;
  const avgResolutionRate = totalCount > 0 ? ((resolvedCount / totalCount) * 100).toFixed(1) : '0.0';
  
  // Calculate average resolution time
  const resolvedComplaints = complaints.filter(c => c.status === 'resolved' && c.resolvedDate);
  let avgResolutionTime = 0;
  if (resolvedComplaints.length > 0) {
    const totalDays = resolvedComplaints.reduce((sum, c) => {
      const submitted = new Date(c.submittedDate);
      const resolved = new Date(c.resolvedDate!);
      const days = Math.ceil((resolved.getTime() - submitted.getTime()) / (1000 * 60 * 60 * 24));
      return sum + days;
    }, 0);
    avgResolutionTime = totalDays / resolvedComplaints.length;
  }
  
  const statsData = [
    ['Total Complaints This Month', totalCount.toString()],
    ['Resolved Complaints', resolvedCount.toString()],
    ['Overall Resolution Rate', `${avgResolutionRate}%`],
    ['Average Resolution Time', `${avgResolutionTime.toFixed(1)} days`],
  ];
  
  autoTable(doc, {
    startY: yPos,
    head: [['Metric', 'Value']],
    body: statsData,
    theme: 'grid',
    headStyles: { fillColor: [147, 51, 234], textColor: [255, 255, 255] },
    columnStyles: { 0: { fontStyle: 'bold' } },
    margin: { left: 14, right: 14 },
  });
  
  yPos = (doc as any).lastAutoTable.finalY + 15;
  
  // Top Issues
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Top Complaints by Votes', 14, yPos);
  
  yPos += 5;
  
  const topComplaints = [...complaints]
    .sort((a, b) => b.votes - a.votes)
    .slice(0, 10)
    .map((c, index) => [
      (index + 1).toString(),
      c.title.substring(0, 50) + (c.title.length > 50 ? '...' : ''),
      c.category.charAt(0).toUpperCase() + c.category.slice(1),
      c.votes.toString(),
      c.status.charAt(0).toUpperCase() + c.status.slice(1),
    ]);
  
  autoTable(doc, {
    startY: yPos,
    head: [['#', 'Complaint Title', 'Category', 'Votes', 'Status']],
    body: topComplaints,
    theme: 'striped',
    headStyles: { fillColor: [147, 51, 234], textColor: [255, 255, 255] },
    margin: { left: 14, right: 14 },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 80 },
      2: { cellWidth: 35 },
      3: { cellWidth: 20 },
      4: { cellWidth: 30 },
    },
  });
  
  // Add footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${pageCount}`,
      105,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
    doc.text(
      'Generated by Municipal Complaint Management System',
      105,
      doc.internal.pageSize.height - 5,
      { align: 'center' }
    );
  }
  
  doc.save(`Monthly_Analytics_Report_${new Date().toISOString().split('T')[0]}.pdf`);
}

export function generateCategoryReportPDF(complaints: Complaint[], categoryName: string, municipalName: string) {
  const doc = new jsPDF();
  
  // Add header
  doc.setFillColor(245, 158, 11); // Amber
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text('Category Report', 105, 20, { align: 'center' });
  
  doc.setFontSize(14);
  doc.text(categoryName, 105, 28, { align: 'center' });
  
  doc.setFontSize(12);
  doc.text(municipalName, 105, 35, { align: 'center' });
  
  doc.setTextColor(0, 0, 0);
  
  let yPos = 50;
  
  // Category Statistics
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Category Statistics', 14, yPos);
  
  yPos += 10;
  
  const totalCount = complaints.length;
  const pendingCount = complaints.filter(c => c.status === 'pending').length;
  const verifiedCount = complaints.filter(c => c.status === 'verified').length;
  const resolvedCount = complaints.filter(c => c.status === 'resolved').length;
  const resolutionRate = totalCount > 0 ? ((resolvedCount / totalCount) * 100).toFixed(1) : '0.0';
  
  const statsData = [
    ['Total Complaints', totalCount.toString()],
    ['Pending', pendingCount.toString()],
    ['In Progress', verifiedCount.toString()],
    ['Resolved', resolvedCount.toString()],
    ['Resolution Rate', `${resolutionRate}%`],
  ];
  
  autoTable(doc, {
    startY: yPos,
    head: [['Metric', 'Count']],
    body: statsData,
    theme: 'grid',
    headStyles: { fillColor: [245, 158, 11], textColor: [255, 255, 255] },
    columnStyles: { 0: { fontStyle: 'bold' } },
    margin: { left: 14, right: 14 },
  });
  
  yPos = (doc as any).lastAutoTable.finalY + 15;
  
  // Recent Complaints
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Recent Complaints', 14, yPos);
  
  yPos += 5;
  
  const recentComplaints = [...complaints]
    .sort((a, b) => new Date(b.submittedDate).getTime() - new Date(a.submittedDate).getTime())
    .slice(0, 15)
    .map(c => [
      c.title.substring(0, 60) + (c.title.length > 60 ? '...' : ''),
      c.location.substring(0, 30) + (c.location.length > 30 ? '...' : ''),
      new Date(c.submittedDate).toLocaleDateString(),
      c.status.charAt(0).toUpperCase() + c.status.slice(1),
    ]);
  
  autoTable(doc, {
    startY: yPos,
    head: [['Complaint', 'Location', 'Date', 'Status']],
    body: recentComplaints,
    theme: 'striped',
    headStyles: { fillColor: [245, 158, 11], textColor: [255, 255, 255] },
    margin: { left: 14, right: 14 },
    columnStyles: {
      0: { cellWidth: 85 },
      1: { cellWidth: 50 },
      2: { cellWidth: 30 },
      3: { cellWidth: 25 },
    },
  });
  
  // Add footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${pageCount}`,
      105,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
    doc.text(
      'Generated by Municipal Complaint Management System',
      105,
      doc.internal.pageSize.height - 5,
      { align: 'center' }
    );
  }
  
  const fileName = `${categoryName.replace(/[^a-z0-9]/gi, '_')}_Report_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
}

export function generateWeeklyPerformancePDF(complaints: Complaint[], municipalName: string) {
  const doc = new jsPDF();
  
  // Add header
  doc.setFillColor(34, 197, 94); // Green
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text('Weekly Performance Report', 105, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.text(municipalName, 105, 30, { align: 'center' });
  
  const weekStart = new Date();
  weekStart.setDate(weekStart.getDate() - 7);
  doc.text(`${weekStart.toLocaleDateString()} - ${new Date().toLocaleDateString()}`, 105, 37, { align: 'center' });
  
  doc.setTextColor(0, 0, 0);
  
  let yPos = 50;
  
  // Department Performance
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Department-wise Performance', 14, yPos);
  
  yPos += 10;
  
  // Group by category
  const categoryGroups: { [key: string]: Complaint[] } = {};
  complaints.forEach(c => {
    if (!categoryGroups[c.category]) {
      categoryGroups[c.category] = [];
    }
    categoryGroups[c.category].push(c);
  });
  
  const deptData = Object.entries(categoryGroups).map(([category, items]) => {
    const resolved = items.filter(c => c.status === 'resolved').length;
    const resolutionRate = items.length > 0 ? ((resolved / items.length) * 100).toFixed(1) : '0.0';
    
    // Calculate avg resolution time
    const resolvedItems = items.filter(c => c.status === 'resolved' && c.resolvedDate);
    let avgTime = 0;
    if (resolvedItems.length > 0) {
      const totalDays = resolvedItems.reduce((sum, c) => {
        const submitted = new Date(c.submittedDate);
        const resolved = new Date(c.resolvedDate!);
        const days = Math.ceil((resolved.getTime() - submitted.getTime()) / (1000 * 60 * 60 * 24));
        return sum + days;
      }, 0);
      avgTime = totalDays / resolvedItems.length;
    }
    
    return [
      category.charAt(0).toUpperCase() + category.slice(1),
      items.length.toString(),
      resolved.toString(),
      `${resolutionRate}%`,
      `${avgTime.toFixed(1)} days`
    ];
  });
  
  autoTable(doc, {
    startY: yPos,
    head: [['Department', 'Total', 'Resolved', 'Resolution Rate', 'Avg Time']],
    body: deptData,
    theme: 'grid',
    headStyles: { fillColor: [34, 197, 94], textColor: [255, 255, 255] },
    margin: { left: 14, right: 14 },
  });
  
  // Add footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${pageCount}`,
      105,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
    doc.text(
      'Generated by Municipal Complaint Management System',
      105,
      doc.internal.pageSize.height - 5,
      { align: 'center' }
    );
  }
  
  doc.save(`Weekly_Performance_Report_${new Date().toISOString().split('T')[0]}.pdf`);
}
